name: Publish package to the Maven Central Repository and GitHub Packages
on:
  release:
    types: [created]
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Import GPG key
        id: import_gpg
        uses: crazy-max/ghaction-import-gpg@v3
        with:
          gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.PASSPHRASE }}
      - name: GPG user IDs
        run: |
          echo "fingerprint: ${{ steps.import_gpg.outputs.fingerprint }}"
          echo "keyid:       ${{ steps.import_gpg.outputs.keyid }}"
          echo "name:        ${{ steps.import_gpg.outputs.name }}"
          echo "email:       ${{ steps.import_gpg.outputs.email }}"
      - name: Set up Java for publishing to Maven Central Repository
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
          server-id: ossrh
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD
          gpg-passphrase: ${{ secrets.PASSPHRASE }}
      #- name: Build package maven
        # run: mvn package
      #- name: Sign package
        #run: |
          #cp target/sample-1.0.0-javadoc.jar target/sample-1.0.0-javadoc.jar.asc
          #cp target/sample-1.0.0-sources.jar target/sample-1.0.0-sources.jar.asc
          #cp target/sample-1.0.0.jar target/sample-1.0.0.jar.asc
          #export GPG_TTY=$(tty)
          #ls
          #gpg --list-secret-keys
          #echo "test" | gpg --clearsign
          #git config --global gpg.program $(which gpg)
          #gpg --keyserver hkp://pgp.mit.edu --send-keys ${{ secrets.PASSPHRASE }}
          #gpg --keyserver hkp://keys.gnupg.net --recv-keys ${{ secrets.PASSPHRASE }}
          #gpg -ab pom.xml
          #gpg -ab target/sample-1.0.0-javadoc.jar
          #echo "duong1"
          #gpg -ab target/sample-1.0.0-sources.jar
          #echo "duong2"
          #gpg -ab target/sample-1.0.0.jar
          #echo "duong3"
      - name: Publish to the Maven Central Repository
        run:  |
          #export GPG_TTY=$(tty)
          gpg --keyserver hkp://pgp.mit.edu --send-keys ${{ secrets.PASSPHRASE }}
          gpg --keyserver hkp://keys.gnupg.net --recv-keys ${{ secrets.PASSPHRASE }}
          mvn deploy
        env:
          MAVEN_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.OSSRH_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Publish to GitHub Packages
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: target/*.jar
          tag: ${{ github.ref }}
          overwrite: true
          file_glob: true
